<a href="https://colab.research.google.com/github/Juan-Matheus/JuanMatheus/blob/main/Investiga%C3%A7%C3%A3o_de_poss%C3%ADveis_erros_com_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

Nesse Projeto Vamos realizar uma investigação da base de dados utilizando o Panda para a descoberta de possíveis erros!!

In [3]:
df=pd.read_csv(r'agricultural_raw_material.csv')

In [4]:
df

,Month,Coarse wool Price,Coarse wool price % Change,Copra Price,Copra price % Change,Cotton Price,Cotton price % Change,Fine wool Price,Fine wool price % Change,Hard log Price,...,Plywood Price,Plywood price % Change,Rubber Price,Rubber price % Change,Softlog Price,Softlog price % Change,Soft sawnwood Price,Soft sawnwood price % Change,Wood pulp Price,Wood pulp price % Change
0,Apr-90,482.34,-,236,-,1.83,-,"1,071.63",-,161.20,...,312.36,-,0.84,-,120.66,-,218.76,-,829.29,-
1,May-90,447.26,-7.27%,234,-0.85%,1.89,3.28%,"1,057.18",-1.35%,172.86,...,350.12,12.09%,0.85,1.19%,124.28,3.00%,213.00,-2.63%,842.51,1.59%
2,Jun-90,440.99,-1.40%,216,-7.69%,1.99,5.29%,898.24,-15.03%,181.67,...,373.94,6.80%,0.85,0.00%,129.45,4.16%,200.00,-6.10%,831.35,-1.32%
3,Jul-90,418.44,-5.11%,205,-5.09%,2.01,1.01%,895.83,-0.27%,187.96,...,378.48,1.21%,0.86,1.18%,124.23,-4.03%,210.05,5.03%,798.83,-3.91%
4,Aug-90,418.44,0.00%,198,-3.41%,1.79,-10.95%,951.22,6.18%,186.13,...,364.60,-3.67%,0.88,2.33%,129.70,4.40%,208.30,-0.83%,818.74,2.49%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356,Dec-19,NaN,NaN,NaN,NaN,1.67,1.21%,NaN,NaN,272.80,...,500.37,-0.22%,1.66,7.79%,NaN,NaN,NaN,NaN,875.00,0.00%
357,Jan-20,NaN,NaN,NaN,NaN,1.74,4.19%,NaN,NaN,272.40,...,499.64,-0.15%,1.68,1.20%,NaN,NaN,NaN,NaN,875.00,0.00%
358,Feb-20,NaN,NaN,NaN,NaN,1.69,-2.87%,NaN,NaN,270.56,...,496.28,-0.67%,1.61,-4.17%,NaN,NaN,NaN,NaN,875.00,0.00%
359,Mar-20,NaN,NaN,NaN,NaN,1.49,-11.83%,NaN,NaN,276.93,...,507.96,2.35%,1.50,-6.83%,NaN,NaN,NaN,NaN,875.00,0.00%
360,Apr-20,NaN,NaN,NaN,NaN,1.40,-6.04%,NaN,NaN,276.24,...,506.68,-0.25%,1.33,-11.33%,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
# 5 primeiras linhas
df.head()

,Month,Coarse wool Price,Coarse wool price % Change,Copra Price,Copra price % Change,Cotton Price,Cotton price % Change,Fine wool Price,Fine wool price % Change,Hard log Price,...,Plywood Price,Plywood price % Change,Rubber Price,Rubber price % Change,Softlog Price,Softlog price % Change,Soft sawnwood Price,Soft sawnwood price % Change,Wood pulp Price,Wood pulp price % Change
0,Apr-90,482.34,-,236,-,1.83,-,"1,071.63",-,161.20,...,312.36,-,0.84,-,120.66,-,218.76,-,829.29,-
1,May-90,447.26,-7.27%,234,-0.85%,1.89,3.28%,"1,057.18",-1.35%,172.86,...,350.12,12.09%,0.85,1.19%,124.28,3.00%,213.00,-2.63%,842.51,1.59%
2,Jun-90,440.99,-1.40%,216,-7.69%,1.99,5.29%,898.24,-15.03%,181.67,...,373.94,6.80%,0.85,0.00%,129.45,4.16%,200.00,-6.10%,831.35,-1.32%
3,Jul-90,418.44,-5.11%,205,-5.09%,2.01,1.01%,895.83,-0.27%,187.96,...,378.48,1.21%,0.86,1.18%,124.23,-4.03%,210.05,5.03%,798.83,-3.91%
4,Aug-90,418.44,0.00%,198,-3.41%,1.79,-10.95%,951.22,6.18%,186.13,...,364.60,-3.67%,0.88,2.33%,129.70,4.40%,208.30,-0.83%,818.74,2.49%

In [7]:
# 5 Últimas linas
df.tail()

,Month,Coarse wool Price,Coarse wool price % Change,Copra Price,Copra price % Change,Cotton Price,Cotton price % Change,Fine wool Price,Fine wool price % Change,Hard log Price,...,Plywood Price,Plywood price % Change,Rubber Price,Rubber price % Change,Softlog Price,Softlog price % Change,Soft sawnwood Price,Soft sawnwood price % Change,Wood pulp Price,Wood pulp price % Change
356,Dec-19,NaN,NaN,NaN,NaN,1.67,1.21%,NaN,NaN,272.80,...,500.37,-0.22%,1.66,7.79%,NaN,NaN,NaN,NaN,875.0,0.00%
357,Jan-20,NaN,NaN,NaN,NaN,1.74,4.19%,NaN,NaN,272.40,...,499.64,-0.15%,1.68,1.20%,NaN,NaN,NaN,NaN,875.0,0.00%
358,Feb-20,NaN,NaN,NaN,NaN,1.69,-2.87%,NaN,NaN,270.56,...,496.28,-0.67%,1.61,-4.17%,NaN,NaN,NaN,NaN,875.0,0.00%
359,Mar-20,NaN,NaN,NaN,NaN,1.49,-11.83%,NaN,NaN,276.93,...,507.96,2.35%,1.50,-6.83%,NaN,NaN,NaN,NaN,875.0,0.00%
360,Apr-20,NaN,NaN,NaN,NaN,1.40,-6.04%,NaN,NaN,276.24,...,506.68,-0.25%,1.33,-11.33%,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
#quantidade de linhas e colunas
df.shape

(361, 25)

In [9]:
#Verificando as colunas
df.columns

Index(['Month', 'Coarse wool Price', 'Coarse wool price % Change',
       'Copra Price', 'Copra price % Change', 'Cotton Price',
       'Cotton price % Change', 'Fine wool Price', 'Fine wool price % Change',
       'Hard log Price', 'Hard log price % Change', 'Hard sawnwood Price',
       'Hard sawnwood price % Change', 'Hide Price', 'Hide price % change',
       'Plywood Price', 'Plywood price % Change', 'Rubber Price',
       'Rubber price % Change', 'Softlog Price', 'Softlog price % Change',
       'Soft sawnwood Price', 'Soft sawnwood price % Change',
       'Wood pulp Price', 'Wood pulp price % Change'],
      dtype='object')

In [10]:
#verificando linhas duplicadas
df.duplicated().sum()

0

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 361 entries, 0 to 360
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Month                         361 non-null    object
 1   Coarse wool Price             327 non-null    object
 2   Coarse wool price % Change    327 non-null    object
 3   Copra Price                   339 non-null    object
 4   Copra price % Change          339 non-null    object
 5   Cotton Price                  361 non-null    float64
 6   Cotton price % Change         361 non-null    object
 7   Fine wool Price               327 non-null    object
 8   Fine wool price % Change      327 non-null    object
 9   Hard log Price                361 non-null    float64
 10  Hard log price % Change       361 non-null    object
 11  Hard sawnwood Price           327 non-null    float64
 12  Hard sawnwood price % Change  327 non-null    object
 13  Hide Price                    327 non-null    float64
 14  Hide price % change           327 non-null    object
 15  Plywood Price                 361 non-null    float64
 16  Plywood price % Change        361 non-null    object
 17  Rubber Price                  361 non-null    float64
 18  Rubber price % Change         361 non-null    object
 19  Softlog Price                 327 non-null    float64
 20  Softlog price % Change        327 non-null    object
 21  Soft sawnwood Price           327 non-null    float64
 22  Soft sawnwood price % Change  327 non-null    object
 23  Wood pulp Price               360 non-null    float64
 24  Wood pulp price % Change      360 non-null    object
dtypes: float64(9), object(16)
memory usage: 70.6+ KB

In [12]:
#verifica a existÊncia de NaN
df.isna().sum()

Month                            0
Coarse wool Price               34
Coarse wool price % Change      34
Copra Price                     22
Copra price % Change            22
Cotton Price                     0
Cotton price % Change            0
Fine wool Price                 34
Fine wool price % Change        34
Hard log Price                   0
Hard log price % Change          0
Hard sawnwood Price             34
Hard sawnwood price % Change    34
Hide Price                      34
Hide price % change             34
Plywood Price                    0
Plywood price % Change           0
Rubber Price                     0
Rubber price % Change            0
Softlog Price                   34
Softlog price % Change          34
Soft sawnwood Price             34
Soft sawnwood price % Change    34
Wood pulp Price                  1
Wood pulp price % Change         1
dtype: int64

In [13]:
# Sumário Estatistico
df.describe()

,Cotton Price,Hard log Price,Hard sawnwood Price,Hide Price,Plywood Price,Rubber Price,Softlog Price,Soft sawnwood Price,Wood pulp Price
count,361.000000,361.000000,327.000000,327.000000,361.000000,361.000000,327.000000,327.000000,360.000000
mean,1.640000,251.034072,707.950367,78.566667,508.216122,1.656427,164.527462,291.061713,696.670889
std,0.513319,65.628406,144.563241,13.690623,89.274718,1.017086,25.596308,34.113959,161.156936
min,0.820000,133.280000,413.370000,28.590000,312.360000,0.490000,119.350000,183.610000,384.000000
25%,1.290000,197.960000,573.470000,69.495000,442.540000,0.860000,145.970000,277.590000,549.777500
50%,1.600000,253.010000,728.710000,77.250000,505.040000,1.440000,160.370000,294.960000,693.580000
75%,1.850000,282.970000,831.635000,86.000000,570.790000,2.060000,180.210000,310.865000,875.000000
max,5.060000,520.810000,973.600000,114.630000,751.810000,6.260000,259.970000,372.600000,966.490000

In [14]:
# sumário estatistico - inclusive para as variáveis categóricas
df.describe(include = "all")

,Month,Coarse wool Price,Coarse wool price % Change,Copra Price,Copra price % Change,Cotton Price,Cotton price % Change,Fine wool Price,Fine wool price % Change,Hard log Price,...,Plywood Price,Plywood price % Change,Rubber Price,Rubber price % Change,Softlog Price,Softlog price % Change,Soft sawnwood Price,Soft sawnwood price % Change,Wood pulp Price,Wood pulp price % Change
count,361,327,327,339,339,361.000000,361,327,327,361.000000,...,361.000000,361,361.000000,361,327.000000,327,327.000000,327,360.000000,360
unique,361,324,293,263,307,NaN,296,325,300,NaN,...,NaN,286,NaN,302,NaN,300,NaN,297,NaN,259
top,Apr-90,418.44,0.69%,412,0.00%,NaN,0.00%,596.02,-0.69%,NaN,...,NaN,0.00%,NaN,0.00%,NaN,9.95%,NaN,-5.18%,NaN,0.00%
freq,1,2,3,4,10,NaN,22,2,3,NaN,...,NaN,8,NaN,28,NaN,3,NaN,3,NaN,71
mean,NaN,NaN,NaN,NaN,NaN,1.640000,NaN,NaN,NaN,251.034072,...,508.216122,NaN,1.656427,NaN,164.527462,NaN,291.061713,NaN,696.670889,NaN
std,NaN,NaN,NaN,NaN,NaN,0.513319,NaN,NaN,NaN,65.628406,...,89.274718,NaN,1.017086,NaN,25.596308,NaN,34.113959,NaN,161.156936,NaN
min,NaN,NaN,NaN,NaN,NaN,0.820000,NaN,NaN,NaN,133.280000,...,312.360000,NaN,0.490000,NaN,119.350000,NaN,183.610000,NaN,384.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,1.290000,NaN,NaN,NaN,197.960000,...,442.540000,NaN,0.860000,NaN,145.970000,NaN,277.590000,NaN,549.777500,NaN
50%,NaN,NaN,NaN,NaN,NaN,1.600000,NaN,NaN,NaN,253.010000,...,505.040000,NaN,1.440000,NaN,160.370000,NaN,294.960000,NaN,693.580000,NaN
75%,NaN,NaN,NaN,NaN,NaN,1.850000,NaN,NaN,NaN,282.970000,...,570.790000,NaN,2.060000,NaN,180.210000,NaN,310.865000,NaN,875.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,5.060000,NaN,NaN,NaN,520.810000,...,751.810000,NaN,6.260000,NaN,259.970000,NaN,372.600000,NaN,966.490000,NaN

In [15]:
# quantidade de valores únicos em cada coluna
df.nunique()

Month                           361
Coarse wool Price               324
Coarse wool price % Change      293
Copra Price                     263
Copra price % Change            307
Cotton Price                    134
Cotton price % Change           296
Fine wool Price                 325
Fine wool price % Change        300
Hard log Price                  350
Hard log price % Change         325
Hard sawnwood Price             291
Hard sawnwood price % Change    257
Hide Price                      298
Hide price % change             277
Plywood Price                   349
Plywood price % Change          286
Rubber Price                    185
Rubber price % Change           302
Softlog Price                   316
Softlog price % Change          300
Soft sawnwood Price             316
Soft sawnwood price % Change    297
Wood pulp Price                 287
Wood pulp price % Change        259
dtype: int64

In [16]:
#valores únicos
df['Cotton Price'].unique()

array([1.83, 1.89, 1.99, 2.01, 1.79, 1.82, 1.85, 1.87, 1.86, 1.78, 1.7 ,
       1.62, 1.55, 1.5 , 1.4 , 1.36, 1.31, 1.24, 1.22, 1.28, 1.34, 1.41,
       1.44, 1.32, 1.25, 1.17, 1.16, 1.2 , 1.26, 1.33, 1.35, 1.3 , 1.27,
       1.21, 1.53, 1.8 , 1.9 , 1.69, 1.66, 1.63, 1.71, 1.92, 2.11, 2.23,
       2.44, 2.51, 2.53, 2.  , 1.93, 1.88, 1.97, 1.94, 1.76, 1.68, 1.75,
       1.77, 1.74, 1.64, 1.59, 1.52, 1.51, 1.45, 1.42, 1.54, 1.46, 1.23,
       1.29, 1.12, 1.09, 1.05, 1.02, 0.97, 1.18, 1.13, 1.1 , 1.  , 0.96,
       0.91, 0.82, 0.84, 0.95, 0.94, 0.93, 0.88, 1.03, 1.08, 1.15, 1.6 ,
       1.67, 1.19, 1.07, 1.47, 1.61, 1.65, 1.72, 1.37, 1.14, 1.43, 1.58,
       2.05, 2.31, 2.79, 3.41, 3.7 , 3.94, 4.7 , 5.06, 4.78, 3.65, 3.18,
       2.69, 2.52, 2.58, 2.1 , 2.22, 2.19, 2.2 , 1.95, 1.81, 1.84, 1.98,
       2.08, 2.03, 2.04, 2.07, 2.14, 1.49, 1.48, 1.73, 1.91, 2.15, 2.12,
       1.56, 1.57])

In [17]:
#ordenando as colunas
df.sort_values(["Cotton Price"])

,Month,Coarse wool Price,Coarse wool price % Change,Copra Price,Copra price % Change,Cotton Price,Cotton price % Change,Fine wool Price,Fine wool price % Change,Hard log Price,...,Plywood Price,Plywood price % Change,Rubber Price,Rubber price % Change,Softlog Price,Softlog price % Change,Soft sawnwood Price,Soft sawnwood price % Change,Wood pulp Price,Wood pulp price % Change
138,Oct-01,330.29,-3.01%,195,-7.14%,0.82,-9.89%,441.98,-15.68%,149.64,...,404.02,-1.90%,0.54,-6.90%,144.92,-9.63%,274.31,-3.04%,440.56,4.70%
139,Nov-01,335.91,1.70%,202,3.59%,0.84,2.44%,466.09,5.45%,142.50,...,400.63,-0.84%,0.51,-5.56%,152.06,4.93%,289.10,5.39%,442.42,0.42%
145,May-02,519.78,-1.01%,263,7.79%,0.88,-3.30%,619.09,0.74%,153.43,...,391.35,4.68%,0.70,4.48%,141.19,-6.18%,254.10,2.38%,447.37,6.22%
137,Sep-01,340.53,-2.41%,210,-10.64%,0.91,-5.21%,524.19,-15.17%,156.31,...,411.85,2.21%,0.58,-1.69%,160.37,2.00%,282.92,-3.18%,420.80,1.82%
144,Apr-02,525.07,-0.77%,244,5.17%,0.91,-2.15%,614.56,1.15%,143.94,...,373.84,0.09%,0.67,0.00%,150.49,4.28%,248.19,2.78%,421.18,-1.87%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248,Dec-10,883.84,-0.64%,"1,154.00",13.89%,3.70,8.50%,"1,266.17",-0.69%,306.54,...,582.38,0.24%,4.75,10.21%,149.49,6.01%,287.84,6.08%,880.79,-1.83%
249,Jan-11,"1,011.45",14.44%,"1,354.00",17.33%,3.94,6.49%,"1,549.40",22.37%,315.32,...,584.49,0.36%,5.52,16.21%,152.47,1.99%,291.81,1.38%,879.09,-0.19%
250,Feb-11,"1,060.91",4.89%,"1,503.00",11.00%,4.70,19.29%,"1,633.11",5.40%,328.63,...,588.69,0.72%,6.26,13.41%,150.29,-1.43%,262.96,-9.89%,885.82,0.77%
252,Apr-11,"1,309.26",8.25%,"1,421.00",11.02%,4.78,-5.53%,"1,743.67",2.39%,343.50,...,596.33,0.69%,5.85,7.93%,156.19,4.06%,275.40,1.78%,937.44,3.06%
251,Mar-11,"1,209.44",14.00%,"1,280.00",-14.84%,5.06,7.66%,"1,702.98",4.28%,334.76,...,592.22,0.60%,5.42,-13.42%,150.10,-0.13%,270.59,2.90%,909.63,2.69%

In [18]:
#Coluna com a média dos preços
media_precos = ['Cotton Price', 'Rubber Price']
df['mean'] = df[media_precos].mean(axis = 1)

In [19]:
df.head()

,Month,Coarse wool Price,Coarse wool price % Change,Copra Price,Copra price % Change,Cotton Price,Cotton price % Change,Fine wool Price,Fine wool price % Change,Hard log Price,...,Plywood price % Change,Rubber Price,Rubber price % Change,Softlog Price,Softlog price % Change,Soft sawnwood Price,Soft sawnwood price % Change,Wood pulp Price,Wood pulp price % Change,mean
0,Apr-90,482.34,-,236,-,1.83,-,"1,071.63",-,161.20,...,-,0.84,-,120.66,-,218.76,-,829.29,-,1.335
1,May-90,447.26,-7.27%,234,-0.85%,1.89,3.28%,"1,057.18",-1.35%,172.86,...,12.09%,0.85,1.19%,124.28,3.00%,213.00,-2.63%,842.51,1.59%,1.370
2,Jun-90,440.99,-1.40%,216,-7.69%,1.99,5.29%,898.24,-15.03%,181.67,...,6.80%,0.85,0.00%,129.45,4.16%,200.00,-6.10%,831.35,-1.32%,1.420
3,Jul-90,418.44,-5.11%,205,-5.09%,2.01,1.01%,895.83,-0.27%,187.96,...,1.21%,0.86,1.18%,124.23,-4.03%,210.05,5.03%,798.83,-3.91%,1.435
4,Aug-90,418.44,0.00%,198,-3.41%,1.79,-10.95%,951.22,6.18%,186.13,...,-3.67%,0.88,2.33%,129.70,4.40%,208.30,-0.83%,818.74,2.49%,1.335

In [20]:
# Primeiro modo de Consulta
df.query('(mean >=1.500 )')

,Month,Coarse wool Price,Coarse wool price % Change,Copra Price,Copra price % Change,Cotton Price,Cotton price % Change,Fine wool Price,Fine wool price % Change,Hard log Price,...,Plywood price % Change,Rubber Price,Rubber price % Change,Softlog Price,Softlog price % Change,Soft sawnwood Price,Soft sawnwood price % Change,Wood pulp Price,Wood pulp price % Change,mean
51,Jul-94,411.95,4.43%,430,0.00%,1.80,-4.76%,773.5,-0.76%,331.98,...,3.20%,1.25,19.05%,202.82,3.85%,285.23,-12.60%,555.99,4.45%,1.525
54,Oct-94,433.45,-2.48%,409,-3.99%,1.63,-1.81%,824.64,-5.87%,291.55,...,0.25%,1.37,7.87%,187.33,-3.37%,285.91,-2.60%,677.68,11.58%,1.500
55,Nov-94,446.07,2.91%,464,13.45%,1.71,4.91%,881.7,6.92%,279.43,...,-0.92%,1.34,-2.19%,212.30,13.33%,286.32,0.14%,687.57,1.46%,1.525
56,Dec-94,426.04,-4.49%,469,1.08%,1.92,12.28%,878.41,-0.37%,247.96,...,-4.04%,1.47,9.70%,188.58,-11.17%,306.55,7.07%,674.32,-1.93%,1.695
57,Jan-95,447.06,4.93%,414,-11.73%,2.11,9.90%,904.18,2.93%,248.42,...,2.04%,1.64,11.56%,211.77,12.30%,281.66,-8.12%,690.45,2.39%,1.875
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354,Oct-19,NaN,NaN,NaN,NaN,1.63,3.82%,NaN,NaN,275.34,...,-0.62%,1.43,-4.67%,NaN,NaN,NaN,NaN,875.00,0.00%,1.530
355,Nov-19,NaN,NaN,NaN,NaN,1.65,1.23%,NaN,NaN,273.40,...,-0.71%,1.54,7.69%,NaN,NaN,NaN,NaN,875.00,0.00%,1.595
356,Dec-19,NaN,NaN,NaN,NaN,1.67,1.21%,NaN,NaN,272.80,...,-0.22%,1.66,7.79%,NaN,NaN,NaN,NaN,875.00,0.00%,1.665
357,Jan-20,NaN,NaN,NaN,NaN,1.74,4.19%,NaN,NaN,272.40,...,-0.15%,1.68,1.20%,NaN,NaN,NaN,NaN,875.00,0.00%,1.710
358,Feb-20,NaN,NaN,NaN,NaN,1.69,-2.87%,NaN,NaN,270.56,...,-0.67%,1.61,-4.17%,NaN,NaN,NaN,NaN,875.00,0.00%,1.650